// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportStock.Api.Data;

#nullable disable

namespace SportStock.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArticleSportFournisseur", b =>
                {
                    b.Property<int>("ArticlesFournisId")
                        .HasColumnType("integer");

                    b.Property<int>("FournisseursId")
                        .HasColumnType("integer");

                    b.HasKey("ArticlesFournisId", "FournisseursId");

                    b.HasIndex("FournisseursId");

                    b.ToTable("ArticleFournisseur", (string)null);
                });

            modelBuilder.Entity("SportStock.Api.Models.ArticleSport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric");

                    b.Property<int>("QuantiteEnStock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Articles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ArticleSport");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SportStock.Api.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SportStock.Api.Models.EmplacementStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Allee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArticleSportId")
                        .HasColumnType("integer");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rayon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArticleSportId")
                        .IsUnique();

                    b.ToTable("Emplacements");
                });

            modelBuilder.Entity("SportStock.Api.Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NomSociete")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("SportStock.Api.Models.VetementSport", b =>
                {
                    b.HasBaseType("SportStock.Api.Models.ArticleSport");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Matiere")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Taille")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("VetementSport");
                });

            modelBuilder.Entity("ArticleSportFournisseur", b =>
                {
                    b.HasOne("SportStock.Api.Models.ArticleSport", null)
                        .WithMany()
                        .HasForeignKey("ArticlesFournisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportStock.Api.Models.Fournisseur", null)
                        .WithMany()
                        .HasForeignKey("FournisseursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportStock.Api.Models.ArticleSport", b =>
                {
                    b.HasOne("SportStock.Api.Models.Categorie", "Categorie")
                        .WithMany("Articles")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("SportStock.Api.Models.EmplacementStock", b =>
                {
                    b.HasOne("SportStock.Api.Models.ArticleSport", "Article")
                        .WithOne("EmplacementStock")
                        .HasForeignKey("SportStock.Api.Models.EmplacementStock", "ArticleSportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("SportStock.Api.Models.ArticleSport", b =>
                {
                    b.Navigation("EmplacementStock");
                });

            modelBuilder.Entity("SportStock.Api.Models.Categorie", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
